name: codacy-coverage-reporter

on: push

jobs:
  install-and-test:
    name: install and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: Jest
      uses: rkusa/jest-action@master
      with:
        ***REMOVED***
