name: codacy-coverage-reporter

on: push

jobs:
  install-and-test:
    name: install and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: Jest
      uses: rkusa/jest-action@master
      ***REMOVED*** 

  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          ***REMOVED***
          coverage-reports: clover.xml
          